### ISSUE TITLE
qint64 property support?

### ISSUE THREAD

**Issue by JoeyJoeJoeJrShabadoo** [devbean/log4qt#3]
I recently updated from an older version (years old) using your repo and realized that the qint64 support is now gone (Factory::doSetObjectProperty(), OptionConverter::toQInt64()). Is this intended or by accident? I'm asking because now it's not possible anymore to set maximumFileSize of a RollingFileAppender.

Alex

**Comment by devbean** [comment]
I just port the older version to support Qt 5 and didn't modify any code if not necessary, so if any qint64 bugs must because of something by accident. I'll check it as soon as possible, and thank you for your reply! If you could, please send a pull request, thank you for that, too!

**Comment by devbean** [comment]
I think we could close this issue for we had merged the request. If you have any problems for this issue, please reopen it.
